version: "3.9"
services:
    db:
        image: mysql:5.7
        container_name: db
        networks:
          - db
          - backend
        volumes: 
          - database-volume:/var/lib/mysql
          - ./db:/docker-entrypoint-initdb.d
        environment:
          - MYSQL_ROOT_PASSWORD=letmein
          - MYSQL_DATABASE=posts
          - MYSQL_USER=worker
          - MYSQL_PASSWORD=replicant
    lb: 
      image: nginx:latest
      container_name: lb
      networks:
        - frontend
        - backend
      volumes: 
        - ./ws/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./ws/default:/etc/nginx/sites-enabled
      ports:
        - 192.168.33.30:80:80
      depends_on:
        - db
    ws1:
      build: .
      container_name: ws1
      networks:
        - backend
        - db
      depends_on:
        - db        
    ws2:
      build: .
      container_name: ws2
      networks:
        - backend        
        - db
      depends_on:
        - db
    ws3:
      build: .
      container_name: ws3
      networks:
        - backend
        - db
      depends_on:
        - db

      
volumes:
    database-volume: {}
        
networks:
    frontend:
    backend:
    db: